banks_dict = {
    "SBIN": "State Bank Of India",
    "HDFC": "HDFC Bank Ltd.",
    "BOBA": "Bank of Baroda",
    "UBIN": "Union Bank Of India",
    "PNBN": "Punjab National Bank",
    "KMBK": "Kotak Mahindra Bank",
    "AXIS": "Axis Bank Ltd.",
    "CNRA": "Canara Bank",
    "ICIC": "ICICI Bank Ltd.",
    "BOIN": "Bank Of India",
    "INDB": "Indian Bank",
    "AIRB": "Airtel Payments Bank Ltd.",
    "IPPB": "India Post Payments Bank Ltd.",
    "FEDB": "Federal Bank Ltd.",
    "CBIN": "Central Bank of India",
    "IOBK": "Indian Overseas Bank",
    "UCOB": "UCO Bank",
    "IDBI": "IDBI Bank",
    "INDI": "Indusind Bank Ltd.",
    "BOMA": "Bank of Maharashtra",
    "FINB": "Fino Payments Bank Limited",
    "YESB": "Yes Bank Ltd.",
    "KBNK": "Karnataka Bank",
    "IDFC": "IDFC First Bank Ltd.",
    "KVBK": "Karur Vysya Bank",
    "J&KB": "The Jammu & Kashmir Bank Limited",
    "BDBK": "Bandhan Bank Limited",
    "SIBK": "The South Indian Bank Limited",
    "TOTS": "Tri O Tech Solutions Private Limited",
    "AUSB": "AU Small Finance Bank",
    "UJSF": "Ujjivan Small Finance Bank Limited",
    "CUBK": "City Union Bank",
    "PSBK": "Punjab & Sind Bank",
    "TMBK": "Tamilnad Mercantile Bank Limited",
    "EQSF": "Equitas Small Finance Bank Ltd.",
    "KGBK": "Kerala Gramin Bank",
    "KGBN": "Karnataka Gramin Bank",
    "APGB": "Andhra Pradesh Grameena Vikas Bank - IMPS",
    "DBSB": "DBS Bank India Limited",
    "RMGB": "Rajasthan Marudhara Gramin Bank",
    "MGBK": "Maharashtra Gramin Bank",
    "SCBK": "Standard Chartered Bank",
    "ESFB": "ESAF Small Finance Bank Ltd.",
    "SCOB": "Saraswat Co-operative Bank",
    "BUPB": "Baroda U.P. Bank",
    "SHGB": "Sarva Haryana Gramin Bank",
    "JIOB": "Jio Payments Bank Limited",
    "RBLB": "RBL Bank Ltd."
}

print(banks_dict["SBIN"])